# Generated by Django 3.2.6 on 2021-08-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(error_messages={'invalid': 'Enter a valid value', 'required': 'This field is required'}, null=True),  # noqa: E501
        ),
    ]
