# Generated by Django 3.2.6 on 2021-09-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210902_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Двоешник'), ('p', 'Троешник'), ('w', 'хорошист'), ('x', 'задрот')], max_length=30),
        ),
    ]
