# Generated by Django 3.2.6 on 2021-08-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='execution_time',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='logger',
            name='method',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='logger',
            name='path',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
