# Generated by Django 3.2.6 on 2021-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210909_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sub',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Двоешник'), ('p', 'Троешник'), ('w', 'хорошист'), ('x', 'задрот')], max_length=30),
        ),
    ]
