# Generated by Django 3.2.6 on 2021-08-29 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_headman'),
        ('students', '0005_auto_20210828_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
