# Generated by Django 3.2.6 on 2021-11-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_logger_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='execution_time',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
