# Generated by Django 3.2.6 on 2021-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('currency', models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('RUR', 'Ruble')], max_length=4)),
                ('source', models.CharField(default='privatbank', max_length=4)),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('buy_price', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
