# Generated by Django 3.2.6 on 2021-08-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='buy_price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sale_price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='source',
            field=models.CharField(default='privatbank', max_length=20),
        ),
    ]
