# Generated by Django 3.2.6 on 2021-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210831_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
