# Generated by Django 3.2.6 on 2021-08-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_exchange_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='source',
            new_name='bank',
        ),
        migrations.AlterField(
            model_name='exchange',
            name='currency',
            field=models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('RUR', 'Ruble'), ('BTC', 'BitCoin')], max_length=4),
        ),
    ]
