# Generated by Django 3.2.6 on 2021-08-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20210831_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='currency',
            field=models.CharField(max_length=4),
        ),
    ]
