# Generated by Django 3.2.6 on 2021-09-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_exchange_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MONO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=4)),
                ('bank', models.CharField(default='NACBANK', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('buy_price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
