# Generated by Django 3.2.6 on 2021-09-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_mono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MONO',
        ),
    ]
