# Generated by Django 3.2.6 on 2021-08-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hours_to_take',
            field=models.IntegerField(default=32),
        ),
    ]
