# Generated by Django 3.2.6 on 2021-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_number_of_students_engaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number_of_students_engaged',
            field=models.IntegerField(null=True),
        ),
    ]
