# Generated by Django 3.2.6 on 2021-08-29 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210828_2349'),
        ('group', '0004_alter_group_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='headman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headed_group', to='students.student'),
        ),
    ]
