# Generated by Django 3.2.6 on 2021-09-23 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('group', '0004_alter_group_number_of_students_engaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='number_of_students_engaged',
        ),
        migrations.AlterField(
            model_name='group',
            name='curator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
