# Generated by Django 3.2.6 on 2021-08-30 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_group'),
        ('group', '0011_alter_group_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='headman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headman', to='students.student'),
        ),
    ]
