# Generated by Django 3.2.6 on 2021-08-31 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_group'),
        ('group', '0012_alter_group_headman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='headman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headed_group', to='students.student'),
        ),
    ]
